// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: extension.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Proto_Ext_Extension_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var data: Proto_Ext_Extension_RequestData {
    get {return _data ?? Proto_Ext_Extension_RequestData()}
    set {_data = newValue}
  }
  /// Returns true if `data` has been explicitly set.
  public var hasData: Bool {return self._data != nil}
  /// Clears the value of `data`. Subsequent reads from it will return its default value.
  public mutating func clearData() {self._data = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _data: Proto_Ext_Extension_RequestData? = nil
}

public struct Proto_Ext_Extension_RequestData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: Proto_Ext_Extension_RequestData.OneOf_Payload? = nil

  public var ui: Proto_Ext_Ui_Request {
    get {
      if case .ui(let v)? = payload {return v}
      return Proto_Ext_Ui_Request()
    }
    set {payload = .ui(newValue)}
  }

  public var app: Proto_Ext_Application_Request {
    get {
      if case .app(let v)? = payload {return v}
      return Proto_Ext_Application_Request()
    }
    set {payload = .app(newValue)}
  }

  public var clipboard: Proto_Ext_Clipboard_Request {
    get {
      if case .clipboard(let v)? = payload {return v}
      return Proto_Ext_Clipboard_Request()
    }
    set {payload = .clipboard(newValue)}
  }

  public var storage: Proto_Ext_Storage_Request {
    get {
      if case .storage(let v)? = payload {return v}
      return Proto_Ext_Storage_Request()
    }
    set {payload = .storage(newValue)}
  }

  public var oauth: Proto_Ext_Oauth_Request {
    get {
      if case .oauth(let v)? = payload {return v}
      return Proto_Ext_Oauth_Request()
    }
    set {payload = .oauth(newValue)}
  }

  public var fileSearch: Proto_Ext_FileSearch_Request {
    get {
      if case .fileSearch(let v)? = payload {return v}
      return Proto_Ext_FileSearch_Request()
    }
    set {payload = .fileSearch(newValue)}
  }

  public var wm: Proto_Ext_Wm_Request {
    get {
      if case .wm(let v)? = payload {return v}
      return Proto_Ext_Wm_Request()
    }
    set {payload = .wm(newValue)}
  }

  public var command: Proto_Ext_Command_Request {
    get {
      if case .command(let v)? = payload {return v}
      return Proto_Ext_Command_Request()
    }
    set {payload = .command(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case ui(Proto_Ext_Ui_Request)
    case app(Proto_Ext_Application_Request)
    case clipboard(Proto_Ext_Clipboard_Request)
    case storage(Proto_Ext_Storage_Request)
    case oauth(Proto_Ext_Oauth_Request)
    case fileSearch(Proto_Ext_FileSearch_Request)
    case wm(Proto_Ext_Wm_Request)
    case command(Proto_Ext_Command_Request)

  }

  public init() {}
}

public struct Proto_Ext_Extension_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var result: Proto_Ext_Extension_Response.OneOf_Result? = nil

  public var data: Proto_Ext_Extension_ResponseData {
    get {
      if case .data(let v)? = result {return v}
      return Proto_Ext_Extension_ResponseData()
    }
    set {result = .data(newValue)}
  }

  public var error: Proto_Ext_Common_ErrorResponse {
    get {
      if case .error(let v)? = result {return v}
      return Proto_Ext_Common_ErrorResponse()
    }
    set {result = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Result: Equatable, Sendable {
    case data(Proto_Ext_Extension_ResponseData)
    case error(Proto_Ext_Common_ErrorResponse)

  }

  public init() {}
}

public struct Proto_Ext_Extension_ResponseData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: Proto_Ext_Extension_ResponseData.OneOf_Payload? = nil

  public var ui: Proto_Ext_Ui_Response {
    get {
      if case .ui(let v)? = payload {return v}
      return Proto_Ext_Ui_Response()
    }
    set {payload = .ui(newValue)}
  }

  public var app: Proto_Ext_Application_Response {
    get {
      if case .app(let v)? = payload {return v}
      return Proto_Ext_Application_Response()
    }
    set {payload = .app(newValue)}
  }

  public var clipboard: Proto_Ext_Clipboard_Response {
    get {
      if case .clipboard(let v)? = payload {return v}
      return Proto_Ext_Clipboard_Response()
    }
    set {payload = .clipboard(newValue)}
  }

  public var storage: Proto_Ext_Storage_Response {
    get {
      if case .storage(let v)? = payload {return v}
      return Proto_Ext_Storage_Response()
    }
    set {payload = .storage(newValue)}
  }

  public var oauth: Proto_Ext_Oauth_Response {
    get {
      if case .oauth(let v)? = payload {return v}
      return Proto_Ext_Oauth_Response()
    }
    set {payload = .oauth(newValue)}
  }

  public var fileSearch: Proto_Ext_FileSearch_Response {
    get {
      if case .fileSearch(let v)? = payload {return v}
      return Proto_Ext_FileSearch_Response()
    }
    set {payload = .fileSearch(newValue)}
  }

  public var wm: Proto_Ext_Wm_Response {
    get {
      if case .wm(let v)? = payload {return v}
      return Proto_Ext_Wm_Response()
    }
    set {payload = .wm(newValue)}
  }

  public var command: Proto_Ext_Command_Response {
    get {
      if case .command(let v)? = payload {return v}
      return Proto_Ext_Command_Response()
    }
    set {payload = .command(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case ui(Proto_Ext_Ui_Response)
    case app(Proto_Ext_Application_Response)
    case clipboard(Proto_Ext_Clipboard_Response)
    case storage(Proto_Ext_Storage_Response)
    case oauth(Proto_Ext_Oauth_Response)
    case fileSearch(Proto_Ext_FileSearch_Response)
    case wm(Proto_Ext_Wm_Response)
    case command(Proto_Ext_Command_Response)

  }

  public init() {}
}

public struct Proto_Ext_Extension_Event: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var payload: Proto_Ext_Extension_Event.OneOf_Payload? = nil

  public var generic: Proto_Ext_Extension_GenericEventData {
    get {
      if case .generic(let v)? = payload {return v}
      return Proto_Ext_Extension_GenericEventData()
    }
    set {payload = .generic(newValue)}
  }

  public var crash: Proto_Ext_Extension_CrashEventData {
    get {
      if case .crash(let v)? = payload {return v}
      return Proto_Ext_Extension_CrashEventData()
    }
    set {payload = .crash(newValue)}
  }

  public var launch: Proto_Ext_Extension_LaunchEventData {
    get {
      if case .launch(let v)? = payload {return v}
      return Proto_Ext_Extension_LaunchEventData()
    }
    set {payload = .launch(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case generic(Proto_Ext_Extension_GenericEventData)
    case crash(Proto_Ext_Extension_CrashEventData)
    case launch(Proto_Ext_Extension_LaunchEventData)

  }

  public init() {}
}

public struct Proto_Ext_Extension_CrashEventData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var text: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proto_Ext_Extension_GenericEventData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var json: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proto_Ext_Extension_LaunchEventData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var extensionName: String = String()

  public var commandName: String = String()

  public var mode: Proto_Ext_Manager_CommandMode = .view

  public var entrypoint: String = String()

  public var assetPath: String = String()

  public var supportPath: String = String()

  public var preferenceValues: Dictionary<String,SwiftProtobuf.Google_Protobuf_Value> = [:]

  public var argumentValues: Dictionary<String,SwiftProtobuf.Google_Protobuf_Value> = [:]

  public var isRaycast: Bool = false

  public var ownerOrAuthorName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.ext.extension"

extension Proto_Ext_Extension_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    try { if let v = self._data {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_Request, rhs: Proto_Ext_Extension_Request) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs._data != rhs._data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Extension_RequestData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ui\0\u{1}app\0\u{1}clipboard\0\u{1}storage\0\u{1}oauth\0\u{3}file_search\0\u{1}wm\0\u{1}command\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Proto_Ext_Ui_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .ui(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .ui(v)
        }
      }()
      case 2: try {
        var v: Proto_Ext_Application_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .app(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .app(v)
        }
      }()
      case 3: try {
        var v: Proto_Ext_Clipboard_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clipboard(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clipboard(v)
        }
      }()
      case 4: try {
        var v: Proto_Ext_Storage_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .storage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .storage(v)
        }
      }()
      case 5: try {
        var v: Proto_Ext_Oauth_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .oauth(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .oauth(v)
        }
      }()
      case 6: try {
        var v: Proto_Ext_FileSearch_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .fileSearch(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .fileSearch(v)
        }
      }()
      case 7: try {
        var v: Proto_Ext_Wm_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .wm(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .wm(v)
        }
      }()
      case 8: try {
        var v: Proto_Ext_Command_Request?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .command(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .command(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .ui?: try {
      guard case .ui(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .app?: try {
      guard case .app(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .clipboard?: try {
      guard case .clipboard(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .storage?: try {
      guard case .storage(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .oauth?: try {
      guard case .oauth(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .fileSearch?: try {
      guard case .fileSearch(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .wm?: try {
      guard case .wm(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .command?: try {
      guard case .command(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_RequestData, rhs: Proto_Ext_Extension_RequestData) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Extension_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}data\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try {
        var v: Proto_Ext_Extension_ResponseData?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .data(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .data(v)
        }
      }()
      case 3: try {
        var v: Proto_Ext_Common_ErrorResponse?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .error(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    switch self.result {
    case .data?: try {
      guard case .data(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .error?: try {
      guard case .error(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_Response, rhs: Proto_Ext_Extension_Response) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Extension_ResponseData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResponseData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ui\0\u{1}app\0\u{1}clipboard\0\u{1}storage\0\u{1}oauth\0\u{3}file_search\0\u{1}wm\0\u{1}command\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Proto_Ext_Ui_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .ui(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .ui(v)
        }
      }()
      case 2: try {
        var v: Proto_Ext_Application_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .app(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .app(v)
        }
      }()
      case 3: try {
        var v: Proto_Ext_Clipboard_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clipboard(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clipboard(v)
        }
      }()
      case 4: try {
        var v: Proto_Ext_Storage_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .storage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .storage(v)
        }
      }()
      case 5: try {
        var v: Proto_Ext_Oauth_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .oauth(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .oauth(v)
        }
      }()
      case 6: try {
        var v: Proto_Ext_FileSearch_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .fileSearch(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .fileSearch(v)
        }
      }()
      case 7: try {
        var v: Proto_Ext_Wm_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .wm(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .wm(v)
        }
      }()
      case 8: try {
        var v: Proto_Ext_Command_Response?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .command(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .command(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .ui?: try {
      guard case .ui(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .app?: try {
      guard case .app(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .clipboard?: try {
      guard case .clipboard(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .storage?: try {
      guard case .storage(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .oauth?: try {
      guard case .oauth(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .fileSearch?: try {
      guard case .fileSearch(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .wm?: try {
      guard case .wm(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .command?: try {
      guard case .command(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_ResponseData, rhs: Proto_Ext_Extension_ResponseData) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Extension_Event: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Event"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}generic\0\u{1}crash\0\u{1}launch\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try {
        var v: Proto_Ext_Extension_GenericEventData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .generic(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .generic(v)
        }
      }()
      case 3: try {
        var v: Proto_Ext_Extension_CrashEventData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .crash(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .crash(v)
        }
      }()
      case 4: try {
        var v: Proto_Ext_Extension_LaunchEventData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .launch(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .launch(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    switch self.payload {
    case .generic?: try {
      guard case .generic(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .crash?: try {
      guard case .crash(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .launch?: try {
      guard case .launch(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_Event, rhs: Proto_Ext_Extension_Event) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Extension_CrashEventData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CrashEventData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_CrashEventData, rhs: Proto_Ext_Extension_CrashEventData) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Extension_GenericEventData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GenericEventData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}json\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.json) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.json.isEmpty {
      try visitor.visitSingularStringField(value: self.json, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_GenericEventData, rhs: Proto_Ext_Extension_GenericEventData) -> Bool {
    if lhs.json != rhs.json {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Extension_LaunchEventData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LaunchEventData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}extension_name\0\u{3}command_name\0\u{1}mode\0\u{1}entrypoint\0\u{3}asset_path\0\u{3}support_path\0\u{3}preference_values\0\u{3}argument_values\0\u{3}is_raycast\0\u{3}owner_or_author_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.extensionName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.commandName) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.entrypoint) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.assetPath) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.supportPath) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Value>.self, value: &self.preferenceValues) }()
      case 8: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Value>.self, value: &self.argumentValues) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.isRaycast) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.ownerOrAuthorName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.extensionName.isEmpty {
      try visitor.visitSingularStringField(value: self.extensionName, fieldNumber: 1)
    }
    if !self.commandName.isEmpty {
      try visitor.visitSingularStringField(value: self.commandName, fieldNumber: 2)
    }
    if self.mode != .view {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 3)
    }
    if !self.entrypoint.isEmpty {
      try visitor.visitSingularStringField(value: self.entrypoint, fieldNumber: 4)
    }
    if !self.assetPath.isEmpty {
      try visitor.visitSingularStringField(value: self.assetPath, fieldNumber: 5)
    }
    if !self.supportPath.isEmpty {
      try visitor.visitSingularStringField(value: self.supportPath, fieldNumber: 6)
    }
    if !self.preferenceValues.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Value>.self, value: self.preferenceValues, fieldNumber: 7)
    }
    if !self.argumentValues.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Value>.self, value: self.argumentValues, fieldNumber: 8)
    }
    if self.isRaycast != false {
      try visitor.visitSingularBoolField(value: self.isRaycast, fieldNumber: 9)
    }
    if !self.ownerOrAuthorName.isEmpty {
      try visitor.visitSingularStringField(value: self.ownerOrAuthorName, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Extension_LaunchEventData, rhs: Proto_Ext_Extension_LaunchEventData) -> Bool {
    if lhs.extensionName != rhs.extensionName {return false}
    if lhs.commandName != rhs.commandName {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.entrypoint != rhs.entrypoint {return false}
    if lhs.assetPath != rhs.assetPath {return false}
    if lhs.supportPath != rhs.supportPath {return false}
    if lhs.preferenceValues != rhs.preferenceValues {return false}
    if lhs.argumentValues != rhs.argumentValues {return false}
    if lhs.isRaycast != rhs.isRaycast {return false}
    if lhs.ownerOrAuthorName != rhs.ownerOrAuthorName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
