// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: oauth.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Proto_Ext_Oauth_RedirectMethod: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case web // = 0
  case app // = 1
  case appUri // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .web
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .web
    case 1: self = .app
    case 2: self = .appUri
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .web: return 0
    case .app: return 1
    case .appUri: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Proto_Ext_Oauth_RedirectMethod] = [
    .web,
    .app,
    .appUri,
  ]

}

public struct Proto_Ext_Oauth_PKCEClientOptions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var name: String = String()

  /// we need to implement image like schema
  public var description_p: String = String()

  public var icon: Proto_Ext_Ui_Image {
    get {return _icon ?? Proto_Ext_Ui_Image()}
    set {_icon = newValue}
  }
  /// Returns true if `icon` has been explicitly set.
  public var hasIcon: Bool {return self._icon != nil}
  /// Clears the value of `icon`. Subsequent reads from it will return its default value.
  public mutating func clearIcon() {self._icon = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: String? = nil
  fileprivate var _icon: Proto_Ext_Ui_Image? = nil
}

public struct Proto_Ext_Oauth_AuthorizeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var client: Proto_Ext_Oauth_PKCEClientOptions {
    get {return _client ?? Proto_Ext_Oauth_PKCEClientOptions()}
    set {_client = newValue}
  }
  /// Returns true if `client` has been explicitly set.
  public var hasClient: Bool {return self._client != nil}
  /// Clears the value of `client`. Subsequent reads from it will return its default value.
  public mutating func clearClient() {self._client = nil}

  public var url: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _client: Proto_Ext_Oauth_PKCEClientOptions? = nil
}

public struct Proto_Ext_Oauth_TokenSet: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var accessToken: String = String()

  public var refreshToken: String {
    get {return _refreshToken ?? String()}
    set {_refreshToken = newValue}
  }
  /// Returns true if `refreshToken` has been explicitly set.
  public var hasRefreshToken: Bool {return self._refreshToken != nil}
  /// Clears the value of `refreshToken`. Subsequent reads from it will return its default value.
  public mutating func clearRefreshToken() {self._refreshToken = nil}

  public var idToken: String {
    get {return _idToken ?? String()}
    set {_idToken = newValue}
  }
  /// Returns true if `idToken` has been explicitly set.
  public var hasIDToken: Bool {return self._idToken != nil}
  /// Clears the value of `idToken`. Subsequent reads from it will return its default value.
  public mutating func clearIDToken() {self._idToken = nil}

  public var expiresIn: UInt32 {
    get {return _expiresIn ?? 0}
    set {_expiresIn = newValue}
  }
  /// Returns true if `expiresIn` has been explicitly set.
  public var hasExpiresIn: Bool {return self._expiresIn != nil}
  /// Clears the value of `expiresIn`. Subsequent reads from it will return its default value.
  public mutating func clearExpiresIn() {self._expiresIn = nil}

  public var scope: String {
    get {return _scope ?? String()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  public var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  public mutating func clearScope() {self._scope = nil}

  public var updatedAt: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _refreshToken: String? = nil
  fileprivate var _idToken: String? = nil
  fileprivate var _expiresIn: UInt32? = nil
  fileprivate var _scope: String? = nil
}

public struct Proto_Ext_Oauth_GetTokensRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var providerID: String {
    get {return _providerID ?? String()}
    set {_providerID = newValue}
  }
  /// Returns true if `providerID` has been explicitly set.
  public var hasProviderID: Bool {return self._providerID != nil}
  /// Clears the value of `providerID`. Subsequent reads from it will return its default value.
  public mutating func clearProviderID() {self._providerID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _providerID: String? = nil
}

public struct Proto_Ext_Oauth_GetTokensResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var tokenSet: Proto_Ext_Oauth_TokenSet {
    get {return _tokenSet ?? Proto_Ext_Oauth_TokenSet()}
    set {_tokenSet = newValue}
  }
  /// Returns true if `tokenSet` has been explicitly set.
  public var hasTokenSet: Bool {return self._tokenSet != nil}
  /// Clears the value of `tokenSet`. Subsequent reads from it will return its default value.
  public mutating func clearTokenSet() {self._tokenSet = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _tokenSet: Proto_Ext_Oauth_TokenSet? = nil
}

public struct Proto_Ext_Oauth_SetTokensRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var providerID: String {
    get {return _providerID ?? String()}
    set {_providerID = newValue}
  }
  /// Returns true if `providerID` has been explicitly set.
  public var hasProviderID: Bool {return self._providerID != nil}
  /// Clears the value of `providerID`. Subsequent reads from it will return its default value.
  public mutating func clearProviderID() {self._providerID = nil}

  public var accessToken: String = String()

  public var refreshToken: String {
    get {return _refreshToken ?? String()}
    set {_refreshToken = newValue}
  }
  /// Returns true if `refreshToken` has been explicitly set.
  public var hasRefreshToken: Bool {return self._refreshToken != nil}
  /// Clears the value of `refreshToken`. Subsequent reads from it will return its default value.
  public mutating func clearRefreshToken() {self._refreshToken = nil}

  public var idToken: String {
    get {return _idToken ?? String()}
    set {_idToken = newValue}
  }
  /// Returns true if `idToken` has been explicitly set.
  public var hasIDToken: Bool {return self._idToken != nil}
  /// Clears the value of `idToken`. Subsequent reads from it will return its default value.
  public mutating func clearIDToken() {self._idToken = nil}

  public var expiresIn: UInt32 {
    get {return _expiresIn ?? 0}
    set {_expiresIn = newValue}
  }
  /// Returns true if `expiresIn` has been explicitly set.
  public var hasExpiresIn: Bool {return self._expiresIn != nil}
  /// Clears the value of `expiresIn`. Subsequent reads from it will return its default value.
  public mutating func clearExpiresIn() {self._expiresIn = nil}

  public var scope: String {
    get {return _scope ?? String()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  public var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  public mutating func clearScope() {self._scope = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _providerID: String? = nil
  fileprivate var _refreshToken: String? = nil
  fileprivate var _idToken: String? = nil
  fileprivate var _expiresIn: UInt32? = nil
  fileprivate var _scope: String? = nil
}

public struct Proto_Ext_Oauth_SetTokensResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proto_Ext_Oauth_RemoveTokensRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var providerID: String {
    get {return _providerID ?? String()}
    set {_providerID = newValue}
  }
  /// Returns true if `providerID` has been explicitly set.
  public var hasProviderID: Bool {return self._providerID != nil}
  /// Clears the value of `providerID`. Subsequent reads from it will return its default value.
  public mutating func clearProviderID() {self._providerID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _providerID: String? = nil
}

public struct Proto_Ext_Oauth_RemoveTokensResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proto_Ext_Oauth_AuthorizeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Proto_Ext_Oauth_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: Proto_Ext_Oauth_Request.OneOf_Payload? = nil

  public var authorize: Proto_Ext_Oauth_AuthorizeRequest {
    get {
      if case .authorize(let v)? = payload {return v}
      return Proto_Ext_Oauth_AuthorizeRequest()
    }
    set {payload = .authorize(newValue)}
  }

  public var getTokens: Proto_Ext_Oauth_GetTokensRequest {
    get {
      if case .getTokens(let v)? = payload {return v}
      return Proto_Ext_Oauth_GetTokensRequest()
    }
    set {payload = .getTokens(newValue)}
  }

  public var setTokens: Proto_Ext_Oauth_SetTokensRequest {
    get {
      if case .setTokens(let v)? = payload {return v}
      return Proto_Ext_Oauth_SetTokensRequest()
    }
    set {payload = .setTokens(newValue)}
  }

  public var removeTokens: Proto_Ext_Oauth_RemoveTokensRequest {
    get {
      if case .removeTokens(let v)? = payload {return v}
      return Proto_Ext_Oauth_RemoveTokensRequest()
    }
    set {payload = .removeTokens(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case authorize(Proto_Ext_Oauth_AuthorizeRequest)
    case getTokens(Proto_Ext_Oauth_GetTokensRequest)
    case setTokens(Proto_Ext_Oauth_SetTokensRequest)
    case removeTokens(Proto_Ext_Oauth_RemoveTokensRequest)

  }

  public init() {}
}

public struct Proto_Ext_Oauth_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: Proto_Ext_Oauth_Response.OneOf_Payload? = nil

  public var authorize: Proto_Ext_Oauth_AuthorizeResponse {
    get {
      if case .authorize(let v)? = payload {return v}
      return Proto_Ext_Oauth_AuthorizeResponse()
    }
    set {payload = .authorize(newValue)}
  }

  public var getTokens: Proto_Ext_Oauth_GetTokensResponse {
    get {
      if case .getTokens(let v)? = payload {return v}
      return Proto_Ext_Oauth_GetTokensResponse()
    }
    set {payload = .getTokens(newValue)}
  }

  public var setTokens: Proto_Ext_Oauth_SetTokensResponse {
    get {
      if case .setTokens(let v)? = payload {return v}
      return Proto_Ext_Oauth_SetTokensResponse()
    }
    set {payload = .setTokens(newValue)}
  }

  public var removeTokens: Proto_Ext_Oauth_RemoveTokensResponse {
    get {
      if case .removeTokens(let v)? = payload {return v}
      return Proto_Ext_Oauth_RemoveTokensResponse()
    }
    set {payload = .removeTokens(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case authorize(Proto_Ext_Oauth_AuthorizeResponse)
    case getTokens(Proto_Ext_Oauth_GetTokensResponse)
    case setTokens(Proto_Ext_Oauth_SetTokensResponse)
    case removeTokens(Proto_Ext_Oauth_RemoveTokensResponse)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto.ext.oauth"

extension Proto_Ext_Oauth_RedirectMethod: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0Web\0\u{1}App\0\u{1}AppURI\0")
}

extension Proto_Ext_Oauth_PKCEClientOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PKCEClientOptions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}description\0\u{1}icon\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._icon) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 3)
    }
    try { if let v = self._icon {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_PKCEClientOptions, rhs: Proto_Ext_Oauth_PKCEClientOptions) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs._icon != rhs._icon {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_AuthorizeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthorizeRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}client\0\u{1}url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._client) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.url) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._client {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_AuthorizeRequest, rhs: Proto_Ext_Oauth_AuthorizeRequest) -> Bool {
    if lhs._client != rhs._client {return false}
    if lhs.url != rhs.url {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_TokenSet: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TokenSet"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}access_token\0\u{3}refresh_token\0\u{3}id_token\0\u{3}expires_in\0\u{1}scope\0\u{3}updated_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._refreshToken) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._idToken) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self._expiresIn) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._scope) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.updatedAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 1)
    }
    try { if let v = self._refreshToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._idToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._expiresIn {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._scope {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    if self.updatedAt != 0 {
      try visitor.visitSingularUInt64Field(value: self.updatedAt, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_TokenSet, rhs: Proto_Ext_Oauth_TokenSet) -> Bool {
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs._refreshToken != rhs._refreshToken {return false}
    if lhs._idToken != rhs._idToken {return false}
    if lhs._expiresIn != rhs._expiresIn {return false}
    if lhs._scope != rhs._scope {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_GetTokensRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetTokensRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}provider_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._providerID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._providerID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_GetTokensRequest, rhs: Proto_Ext_Oauth_GetTokensRequest) -> Bool {
    if lhs._providerID != rhs._providerID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_GetTokensResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetTokensResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}token_set\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._tokenSet) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._tokenSet {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_GetTokensResponse, rhs: Proto_Ext_Oauth_GetTokensResponse) -> Bool {
    if lhs._tokenSet != rhs._tokenSet {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_SetTokensRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetTokensRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}provider_id\0\u{3}access_token\0\u{3}refresh_token\0\u{3}id_token\0\u{3}expires_in\0\u{1}scope\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._providerID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._refreshToken) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._idToken) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self._expiresIn) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._scope) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._providerID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 2)
    }
    try { if let v = self._refreshToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._idToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._expiresIn {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._scope {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_SetTokensRequest, rhs: Proto_Ext_Oauth_SetTokensRequest) -> Bool {
    if lhs._providerID != rhs._providerID {return false}
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs._refreshToken != rhs._refreshToken {return false}
    if lhs._idToken != rhs._idToken {return false}
    if lhs._expiresIn != rhs._expiresIn {return false}
    if lhs._scope != rhs._scope {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_SetTokensResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetTokensResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_SetTokensResponse, rhs: Proto_Ext_Oauth_SetTokensResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_RemoveTokensRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RemoveTokensRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}provider_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._providerID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._providerID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_RemoveTokensRequest, rhs: Proto_Ext_Oauth_RemoveTokensRequest) -> Bool {
    if lhs._providerID != rhs._providerID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_RemoveTokensResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RemoveTokensResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_RemoveTokensResponse, rhs: Proto_Ext_Oauth_RemoveTokensResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_AuthorizeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthorizeResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_AuthorizeResponse, rhs: Proto_Ext_Oauth_AuthorizeResponse) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}authorize\0\u{3}get_tokens\0\u{3}set_tokens\0\u{3}remove_tokens\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Proto_Ext_Oauth_AuthorizeRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .authorize(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .authorize(v)
        }
      }()
      case 2: try {
        var v: Proto_Ext_Oauth_GetTokensRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getTokens(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getTokens(v)
        }
      }()
      case 3: try {
        var v: Proto_Ext_Oauth_SetTokensRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .setTokens(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .setTokens(v)
        }
      }()
      case 4: try {
        var v: Proto_Ext_Oauth_RemoveTokensRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .removeTokens(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .removeTokens(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .authorize?: try {
      guard case .authorize(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getTokens?: try {
      guard case .getTokens(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .setTokens?: try {
      guard case .setTokens(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .removeTokens?: try {
      guard case .removeTokens(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_Request, rhs: Proto_Ext_Oauth_Request) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Ext_Oauth_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}authorize\0\u{3}get_tokens\0\u{3}set_tokens\0\u{3}remove_tokens\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Proto_Ext_Oauth_AuthorizeResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .authorize(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .authorize(v)
        }
      }()
      case 2: try {
        var v: Proto_Ext_Oauth_GetTokensResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getTokens(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getTokens(v)
        }
      }()
      case 3: try {
        var v: Proto_Ext_Oauth_SetTokensResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .setTokens(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .setTokens(v)
        }
      }()
      case 4: try {
        var v: Proto_Ext_Oauth_RemoveTokensResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .removeTokens(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .removeTokens(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .authorize?: try {
      guard case .authorize(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getTokens?: try {
      guard case .getTokens(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .setTokens?: try {
      guard case .setTokens(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .removeTokens?: try {
      guard case .removeTokens(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Proto_Ext_Oauth_Response, rhs: Proto_Ext_Oauth_Response) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
